from app.schemas.anime import (
    AnimeCreate,
    AnimeMetadataUpdate,
    AnimeRead,
    AnimeSummaryRead,
    BangumiInfoItem,
    EpisodeCreate,
    EpisodeDownloadCreate,
    EpisodeRead,
    SeriesCreate,
    SeriesRead,
    WatchProgressRead,
    WatchProgressUpdate,
)
from app.schemas.auth import Token
from app.schemas.config import QBittorrentConfigRead, QBittorrentConfigUpdate
from app.schemas.storage import AnimeStorageRead, StorageStatusRead
from app.schemas.subscription import (
    FansubCandidateRead,
    PreferenceProfileCreate,
    PreferenceProfileRead,
    PreferenceProfileUpdate,
    SubscriptionCheckRead,
    SubscriptionCreate,
    SubscriptionEpisodeRead,
    SubscriptionPreviewCandidateRead,
    SubscriptionPreviewRead,
    SubscriptionPreviewRequest,
    SubscriptionRead,
    SubscriptionUpdate,
)
from app.schemas.qbittorrent import (
    QBittorrentFileRead,
    QBittorrentTorrentAddResult,
    QBittorrentTorrentDownload,
    QBittorrentTorrentRead,
)
from app.schemas.setup import SetupCreate, SetupStatus
from app.schemas.user import PasswordChange, UserCreate, UserRead, UserUpdate
from app.schemas.update import (
    ServerUpdateChannelRead,
    ServerUpdateChannelUpdate,
    ServerUpdateRead,
    ServerUpdateRequest,
    ServerUpdateStatusRead,
)

__all__ = [
    "AnimeCreate",
    "AnimeMetadataUpdate",
    "AnimeRead",
    "AnimeSummaryRead",
    "BangumiInfoItem",
    "EpisodeCreate",
    "EpisodeDownloadCreate",
    "EpisodeRead",
    "SeriesCreate",
    "SeriesRead",
    "QBittorrentConfigRead",
    "QBittorrentConfigUpdate",
    "QBittorrentFileRead",
    "QBittorrentTorrentAddResult",
    "QBittorrentTorrentDownload",
    "QBittorrentTorrentRead",
    "SetupCreate",
    "SetupStatus",
    "AnimeStorageRead",
    "StorageStatusRead",
    "Token",
    "WatchProgressRead",
    "WatchProgressUpdate",
    "UserCreate",
    "PasswordChange",
    "UserRead",
    "UserUpdate",
    "ServerUpdateRead",
    "ServerUpdateRequest",
    "ServerUpdateStatusRead",
    "ServerUpdateChannelRead",
    "ServerUpdateChannelUpdate",
    "FansubCandidateRead",
    "PreferenceProfileCreate",
    "PreferenceProfileRead",
    "PreferenceProfileUpdate",
    "SubscriptionCheckRead",
    "SubscriptionCreate",
    "SubscriptionEpisodeRead",
    "SubscriptionPreviewCandidateRead",
    "SubscriptionPreviewRead",
    "SubscriptionPreviewRequest",
    "SubscriptionRead",
    "SubscriptionUpdate",
]
