"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-26 21:17:36.457666

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bangumi_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_cn', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('air_date', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=128), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('infobox', sa.JSON(), nullable=False),
    sa.Column('download_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anime_bangumi_id'), ['bangumi_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_anime_download_hash'), ['download_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_anime_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('permission_group', sa.Enum('ADMIN', 'USER', 'GUEST', name='permissiongroup'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_anime_id'), ['anime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_id'), ['id'], unique=False)

    op.create_table('watch_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_watch_progress_user_anime')
    )
    with op.batch_alter_table('watch_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watch_progress_anime_id'), ['anime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watch_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watch_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_watch_progress_id'))
        batch_op.drop_index(batch_op.f('ix_watch_progress_anime_id'))

    op.drop_table('watch_progress')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_anime_id'))

    op.drop_table('episodes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anime_id'))
        batch_op.drop_index(batch_op.f('ix_anime_download_hash'))
        batch_op.drop_index(batch_op.f('ix_anime_bangumi_id'))

    op.drop_table('anime')
    # ### end Alembic commands ###
